# SPDX-FileCopyrightText: 2024 Anthony Loiseau <anthony.loiseau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

# This hook is not a test but an action. It should never fail.
# - If given file(s) are already read-only, nothing is done and action succeed
# - If given file(s) are not yet read-only, they are made read-only, success
# - If given file(s) does not exists, nothing is done and action succeed
# - If you forget to override `args` key, action will fail
-   id: set-readonly
    name: set read-only files
    description: change attributes of given files to set them read-only
    entry: hooks/set_readonly
    language: script
    always_run: true
    pass_filenames: false
    # Caller must override args with glob-pattern file names
    # Example: args: ['**.sqlite']
    args: []
