#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 Anthony Loiseau <anthony.loiseau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

set -e
set -u
set -o pipefail

for file in "$@"
do
    chmod --changes --preserve-root a-w -- "${file}"
done
